// <auto-generated />
using Bruno1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bruno1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241021232044_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Bruno1.Models.Folha", b =>
                {
                    b.Property<double>("Valor")
                        .HasColumnType("REAL");

                    b.Property<decimal>("Ano")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FuncionarioId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Mes")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("TEXT");

                    b.HasKey("Valor");

                    b.ToTable("Folhas");
                });
#pragma warning restore 612, 618
        }
    }
}
